blank_issues_enabled: true

contact_links:
  - name: Chat on Telegram
    url: https://t.me/YskraChat
    about: Please ask and answer questions here.
  - name: Chat on Telegram
    url: https://t.me/YskraPlugins
    about: Ask and answer questions about plugins.
  - name: Channel on Telegram
    url: https://t.me/YskraApp
    about: Information and announces about new releases and updates.
