// noinspection SpellCheckingInspection

// import languagesSourse from './languages.json' with { type: 'json' };
// const languages = languagesSourse.map(({ iso_639_1, english_name, name }) => ({ value: iso_639_1, name: `${name || english_name} [${iso_639_1}]` }));
// const codes = languages.map(({ value }) => value);

export default [
  { value: 'kw', name: 'Cornish [kw]' },
  { value: 'ff', name: 'Fulfulde [ff]' },
  { value: 'gn', name: 'Guarani [gn]' },
  { value: 'id', name: 'Bahasa indonesia [id]' },
  { value: 'lu', name: 'Luba-Katanga [lu]' },
  { value: 'nr', name: 'Ndebele [nr]' },
  { value: 'os', name: 'Ossetian; Ossetic [os]' },
  { value: 'ru', name: 'Pусский [ru]' },
  { value: 'se', name: 'Northern Sami [se]' },
  { value: 'so', name: 'Somali [so]' },
  { value: 'es', name: 'Español [es]' },
  { value: 'sv', name: 'svenska [sv]' },
  { value: 'ta', name: 'தமிழ் [ta]' },
  { value: 'te', name: 'తెలుగు [te]' },
  { value: 'tn', name: 'Tswana [tn]' },
  { value: 'uk', name: 'Український [uk]' },
  { value: 'uz', name: 'ozbek [uz]' },
  { value: 'el', name: 'ελληνικά [el]' },
  { value: 'co', name: 'Corsican [co]' },
  { value: 'dv', name: 'Divehi [dv]' },
  { value: 'kk', name: 'қазақ [kk]' },
  { value: 'ki', name: 'Kikuyu [ki]' },
  { value: 'or', name: 'Oriya [or]' },
  { value: 'si', name: 'සිංහල [si]' },
  { value: 'st', name: 'Sotho [st]' },
  { value: 'sr', name: 'Srpski [sr]' },
  { value: 'ss', name: 'Swati [ss]' },
  { value: 'tr', name: 'Türkçe [tr]' },
  { value: 'wa', name: 'Walloon [wa]' },
  { value: 'cn', name: '广州话 / 廣州話 [cn]' },
  { value: 'bi', name: 'Bislama [bi]' },
  { value: 'cr', name: 'Cree [cr]' },
  { value: 'cy', name: 'Cymraeg [cy]' },
  { value: 'eu', name: 'euskera [eu]' },
  { value: 'hz', name: 'Herero [hz]' },
  { value: 'ho', name: 'Hiri Motu [ho]' },
  { value: 'ka', name: 'ქართული [ka]' },
  { value: 'kr', name: 'Kanuri [kr]' },
  { value: 'km', name: 'Khmer [km]' },
  { value: 'kj', name: 'Kuanyama [kj]' },
  { value: 'to', name: 'Tonga [to]' },
  { value: 'vi', name: 'Tiếng Việt [vi]' },
  { value: 'zu', name: 'isiZulu [zu]' },
  { value: 'zh', name: '普通话 [zh]' },
  { value: 'ps', name: 'پښتو [ps]' },
  { value: 'mk', name: 'Macedonian [mk]' },
  { value: 'ae', name: 'Avestan [ae]' },
  { value: 'az', name: 'Azərbaycan [az]' },
  { value: 'ba', name: 'Bashkir [ba]' },
  { value: 'sh', name: 'Serbo-Croatian [sh]' },
  { value: 'lv', name: 'Latviešu [lv]' },
  { value: 'lt', name: 'Lietuvių [lt]' },
  { value: 'ms', name: 'Bahasa melayu [ms]' },
  { value: 'rm', name: 'Raeto-Romance [rm]' },
  { value: 'as', name: 'Assamese [as]' },
  { value: 'gd', name: 'Gaelic [gd]' },
  { value: 'ja', name: '日本語 [ja]' },
  { value: 'ko', name: '한국어/조선말 [ko]' },
  { value: 'ku', name: 'Kurdish [ku]' },
  { value: 'mo', name: 'Moldavian [mo]' },
  { value: 'mn', name: 'Mongolian [mn]' },
  { value: 'nb', name: 'Bokmål [nb]' },
  { value: 'om', name: 'Oromo [om]' },
  { value: 'pi', name: 'Pali [pi]' },
  { value: 'sq', name: 'shqip [sq]' },
  { value: 'vo', name: 'Volapük [vo]' },
  { value: 'bo', name: 'Tibetan [bo]' },
  { value: 'da', name: 'Dansk [da]' },
  { value: 'kl', name: 'Kalaallisut [kl]' },
  { value: 'kn', name: '????? [kn]' },
  { value: 'nl', name: 'Nederlands [nl]' },
  { value: 'nn', name: 'Norwegian Nynorsk [nn]' },
  { value: 'sa', name: 'Sanskrit [sa]' },
  { value: 'am', name: 'Amharic [am]' },
  { value: 'hy', name: 'Armenian [hy]' },
  { value: 'bs', name: 'Bosanski [bs]' },
  { value: 'hr', name: 'Hrvatski [hr]' },
  { value: 'mh', name: 'Marshall [mh]' },
  { value: 'mg', name: 'Malagasy [mg]' },
  { value: 'ne', name: 'Nepali [ne]' },
  { value: 'su', name: 'Sundanese [su]' },
  { value: 'ts', name: 'Tsonga [ts]' },
  { value: 'ug', name: 'Uighur [ug]' },
  { value: 'cs', name: 'Český [cs]' },
  { value: 'jv', name: 'Javanese [jv]' },
  { value: 'ro', name: 'Română [ro]' },
  { value: 'sm', name: 'Samoan [sm]' },
  { value: 'tg', name: 'Tajik [tg]' },
  { value: 'wo', name: 'Wolof [wo]' },
  { value: 'br', name: 'Breton [br]' },
  { value: 'fr', name: 'Français [fr]' },
  { value: 'ga', name: 'Gaeilge [ga]' },
  { value: 'ht', name: 'Haitian; Haitian Creole [ht]' },
  { value: 'kv', name: 'Komi [kv]' },
  { value: 'mi', name: 'Maori [mi]' },
  { value: 'th', name: 'ภาษาไทย [th]' },
  { value: 'xx', name: 'No Language [xx]' },
  { value: 'af', name: 'Afrikaans [af]' },
  { value: 'av', name: 'Avaric [av]' },
  { value: 'bm', name: 'Bamanankan [bm]' },
  { value: 'ca', name: 'Català [ca]' },
  { value: 'ce', name: 'Chechen [ce]' },
  { value: 'de', name: 'Deutsch [de]' },
  { value: 'gv', name: 'Manx [gv]' },
  { value: 'rw', name: 'Kinyarwanda [rw]' },
  { value: 'ky', name: '?????? [ky]' },
  { value: 'ln', name: 'Lingala [ln]' },
  { value: 'sn', name: 'Shona [sn]' },
  { value: 'yi', name: 'Yiddish [yi]' },
  { value: 'be', name: 'беларуская мова [be]' },
  { value: 'cu', name: 'Slavic [cu]' },
  { value: 'dz', name: 'Dzongkha [dz]' },
  { value: 'eo', name: 'Esperanto [eo]' },
  { value: 'fi', name: 'suomi [fi]' },
  { value: 'fy', name: 'Frisian [fy]' },
  { value: 'ie', name: 'Interlingue [ie]' },
  { value: 'ia', name: 'Interlingua [ia]' },
  { value: 'it', name: 'Italiano [it]' },
  { value: 'ng', name: 'Ndonga [ng]' },
  { value: 'pa', name: 'ਪੰਜਾਬੀ [pa]' },
  { value: 'pt', name: 'Português [pt]' },
  { value: 'rn', name: 'Kirundi [rn]' },
  { value: 'fa', name: 'فارسی [fa]' },
  { value: 'ch', name: 'Finu\' Chamorro [ch]' },
  { value: 'cv', name: 'Chuvash [cv]' },
  { value: 'en', name: 'English [en]' },
  { value: 'hu', name: 'Magyar [hu]' },
  { value: 'ii', name: 'Yi [ii]' },
  { value: 'kg', name: 'Kongo [kg]' },
  { value: 'li', name: 'Limburgish [li]' },
  { value: 'ml', name: 'Malayalam [ml]' },
  { value: 'nv', name: 'Navajo [nv]' },
  { value: 'ny', name: 'Chichewa; Nyanja [ny]' },
  { value: 'sg', name: 'Sango [sg]' },
  { value: 'tw', name: 'Twi [tw]' },
  { value: 'ab', name: 'Abkhazian [ab]' },
  { value: 'ar', name: 'العربية [ar]' },
  { value: 'ee', name: 'Èʋegbe [ee]' },
  { value: 'fo', name: 'Faroese [fo]' },
  { value: 'ik', name: 'Inupiaq [ik]' },
  { value: 'ks', name: 'Kashmiri [ks]' },
  { value: 'lb', name: 'Letzeburgesch [lb]' },
  { value: 'nd', name: 'Ndebele [nd]' },
  { value: 'oc', name: 'Occitan [oc]' },
  { value: 'sk', name: 'Slovenčina [sk]' },
  { value: 'tt', name: 'Tatar [tt]' },
  { value: 've', name: 'Venda [ve]' },
  { value: 'ay', name: 'Aymara [ay]' },
  { value: 'fj', name: 'Fijian [fj]' },
  { value: 'gu', name: 'Gujarati [gu]' },
  { value: 'io', name: 'Ido [io]' },
  { value: 'lo', name: 'Lao [lo]' },
  { value: 'la', name: 'Latin [la]' },
  { value: 'no', name: 'Norsk [no]' },
  { value: 'oj', name: 'Ojibwa [oj]' },
  { value: 'pl', name: 'Polski [pl]' },
  { value: 'qu', name: 'Quechua [qu]' },
  { value: 'sl', name: 'Slovenščina [sl]' },
  { value: 'sc', name: 'Sardinian [sc]' },
  { value: 'sw', name: 'Kiswahili [sw]' },
  { value: 'tl', name: 'Tagalog [tl]' },
  { value: 'ur', name: 'اردو [ur]' },
  { value: 'bg', name: 'български език [bg]' },
  { value: 'hi', name: 'हिन्दी [hi]' },
  { value: 'yo', name: 'Èdè Yorùbá [yo]' },
  { value: 'ak', name: 'Akan [ak]' },
  { value: 'an', name: 'Aragonese [an]' },
  { value: 'bn', name: 'বাংলা [bn]' },
  { value: 'et', name: 'Eesti [et]' },
  { value: 'gl', name: 'Galego [gl]' },
  { value: 'ha', name: 'Hausa [ha]' },
  { value: 'ig', name: 'Igbo [ig]' },
  { value: 'iu', name: 'Inuktitut [iu]' },
  { value: 'lg', name: 'Ganda [lg]' },
  { value: 'mr', name: 'Marathi [mr]' },
  { value: 'mt', name: 'Malti [mt]' },
  { value: 'my', name: 'Burmese [my]' },
  { value: 'na', name: 'Nauru [na]' },
  { value: 'sd', name: 'Sindhi [sd]' },
  { value: 'xh', name: 'Xhosa [xh]' },
  { value: 'za', name: 'Zhuang [za]' },
  { value: 'aa', name: 'Afar [aa]' },
  { value: 'is', name: 'Íslenska [is]' },
  { value: 'ty', name: 'Tahitian [ty]' },
  { value: 'ti', name: 'Tigrinya [ti]' },
  { value: 'tk', name: 'Turkmen [tk]' },
  { value: 'he', name: 'עִבְרִית [he]' },
];

export const codes = [
  'kw',
  'ff',
  'gn',
  'id',
  'lu',
  'nr',
  'os',
  'ru',
  'se',
  'so',
  'es',
  'sv',
  'ta',
  'te',
  'tn',
  'uk',
  'uz',
  'el',
  'co',
  'dv',
  'kk',
  'ki',
  'or',
  'si',
  'st',
  'sr',
  'ss',
  'tr',
  'wa',
  'cn',
  'bi',
  'cr',
  'cy',
  'eu',
  'hz',
  'ho',
  'ka',
  'kr',
  'km',
  'kj',
  'to',
  'vi',
  'zu',
  'zh',
  'ps',
  'mk',
  'ae',
  'az',
  'ba',
  'sh',
  'lv',
  'lt',
  'ms',
  'rm',
  'as',
  'gd',
  'ja',
  'ko',
  'ku',
  'mo',
  'mn',
  'nb',
  'om',
  'pi',
  'sq',
  'vo',
  'bo',
  'da',
  'kl',
  'kn',
  'nl',
  'nn',
  'sa',
  'am',
  'hy',
  'bs',
  'hr',
  'mh',
  'mg',
  'ne',
  'su',
  'ts',
  'ug',
  'cs',
  'jv',
  'ro',
  'sm',
  'tg',
  'wo',
  'br',
  'fr',
  'ga',
  'ht',
  'kv',
  'mi',
  'th',
  'xx',
  'af',
  'av',
  'bm',
  'ca',
  'ce',
  'de',
  'gv',
  'rw',
  'ky',
  'ln',
  'sn',
  'yi',
  'be',
  'cu',
  'dz',
  'eo',
  'fi',
  'fy',
  'ie',
  'ia',
  'it',
  'ng',
  'pa',
  'pt',
  'rn',
  'fa',
  'ch',
  'cv',
  'en',
  'hu',
  'ii',
  'kg',
  'li',
  'ml',
  'nv',
  'ny',
  'sg',
  'tw',
  'ab',
  'ar',
  'ee',
  'fo',
  'ik',
  'ks',
  'lb',
  'nd',
  'oc',
  'sk',
  'tt',
  've',
  'ay',
  'fj',
  'gu',
  'io',
  'lo',
  'la',
  'no',
  'oj',
  'pl',
  'qu',
  'sl',
  'sc',
  'sw',
  'tl',
  'ur',
  'bg',
  'hi',
  'yo',
  'ak',
  'an',
  'bn',
  'et',
  'gl',
  'ha',
  'ig',
  'iu',
  'lg',
  'mr',
  'mt',
  'my',
  'na',
  'sd',
  'xh',
  'za',
  'aa',
  'is',
  'ty',
  'ti',
  'tk',
  'he',
];
