name: Deploy

on:
  push:
    branches:
      - master

jobs:
  tests:
    uses: ./.github/workflows/test.yml

  build:
    needs: tests
    uses: ./.github/workflows/build.yml

  deploy-gh-pages:
    needs: build
    uses: ./.github/workflows/deploy-gh-pages.yml
    with:
      spa-artifact: ${{ needs.build.outputs.artifact-id }}

  deploy-cloudflare:
    needs: build
    uses: ./.github/workflows/deploy-cloudflare.yml
    with:
      spa-artifact: ${{ needs.build.outputs.artifact-id }}

  build-container:
    needs: build
    uses: ./.github/workflows/build-container.yml
    with:
      spa-artifact: ${{ needs.build.outputs.artifact-id }}

