name:  Deploy to Cloudflare
on:
  workflow_call:
    inputs:
      spa-artifact:
        description: ID uploaded artifact with static files SPA
        required: true
        type: string
    secrets:
      CLOUDFLARE_API_TOKEN:
        required: true

env:
  directory: dist

jobs:
  deploy:
    name: Deploy to Cloudflare
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    environment:
      name: deploy
      url: ${{ steps.cloudflare.outputs.deployment-url }}
    steps:
      - name: Download SPA artifact by ID
        uses: actions/download-artifact@v5
        with:
          artifact-ids: ${{ inputs.spa-artifact }}
          path: ${{ env.directory }}
          merge-multiple: true

      - name: Create wrangler.toml
        run: |
          cat > wrangler.toml << 'EOF'
            name = "yskra"
            compatibility_date = "$(date -I)"
            assets = { not_found_handling = "single-page-application", directory = "${{ env.directory }}" }
          EOF

      - name: Send assets to Cloudflare
        id: cloudflare
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
